<html>
<link rel="icon" type="images/png" href="favicon.png">
	<head>
		<link rel="stylesheet" href="../style.css">
		<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
</head>

	<body>
		 <?php include('../header4.php');?>
		<?php include('../left_header.php');?>
		<?php include('../right_header.php');?>

			<div id="mid">
				<div id="postpage"> 

							<!-- Start  -->
					<h2>High time India, Pakistan set aside hostilities, says Nawaz Sharif</h2>	
					<a href="posts/Nawaz_Sharif.php"><img src="newsb2.jpg" alt="Images of  Pakistan Prime Minister Nawaz Sharif with  Pakistan Prime Minister Narendar Modi" title="Images of  Pakistan Prime Minister Nawaz Sharif with  Pakistan Prime Minister Narendar Modi"></a><br/>
					<p id="post_para">
						Modi had sprung a surprise when he visited Lahore on the occasion of Sharif's 66th birthday and his granddaughter's wedding on December 25...<br/><br/>

						Modi had sprung a surprise when he visited Lahore on the occasion of Sharif's 66th birthday and his granddaughter's wedding on December 25.

Prime Minister Nawaz Sharif on Wednesday said it is "high time" India and Pakistan set aside their hostilities even as he expressed confidence that the spirit of goodwill generated by his Indian counterpart Narendra Modi's visit to Lahore will persist.<br/><br/>

"The Indian Prime Minister came to Lahore and gave us his few hours. It is high time the countries put aside their hostilities," Sharif said. "Goodwill gestures are the solution to many an ill," he told reporters at Zhob airport in Balochistan. Sharif also thanked Modi for visiting Lahore last week.<br/><br/>

Modi had sprung a surprise when he visited Lahore on the occasion of Sharif's 66th birthday and his granddaughter's wedding on December 25. "It has been agreed that we will re-start the dialogue between Pakistan and India," Sharif said, adding that "progress is being made in bilateral negotiations with India".<br/><br/>

The Pakistan premier's comments came a day after his Advisor on Foreign Affairs Sartaj Aziz said that foreign secretaries of India and Pakistan will meet in Islamabad on January 14-15 to prepare a schedule of meeting for the comprehensive dialogue covering Jammu and Kashmir and other issues. Sharif also expressed optimism that India-Pakistan ties would improve in the days ahead and the "spirit of goodwill generated with Modi's visit will continue to prevail". <br/><br/>
					</p>
					
					<!-- Conclusion  -->


				</div>
			</div>
			<?php include_once('../footer.php'); ?>
	</body>
</html>
